//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ten kod źródłowy został wygenerowany automatycznie przez Microsoft.VSDesigner, wersja 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FakturaWpf.pl.gov.stat.wyszukiwarkaregontest {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: Nie obsłużono opcjonalnego elementu rozszerzenia WSDL „PolicyReference” z obszaru nazw „http://schemas.xmlsoap.org/ws/2004/09/policy”.
    // CODEGEN: Nie obsłużono opcjonalnego elementu rozszerzenia WSDL „EndpointReference” z obszaru nazw „http://www.w3.org/2005/08/addressing”.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="e3", Namespace="http://tempuri.org/")]
    public partial class UslugaBIRzewnPubl : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PobierzCaptchaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SprawdzCaptchaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZalogujOperationCompleted;
        
        private System.Threading.SendOrPostCallback WylogujOperationCompleted;
        
        private System.Threading.SendOrPostCallback DaneSzukajOperationCompleted;
        
        private System.Threading.SendOrPostCallback DanePobierzPelnyRaportOperationCompleted;
        
        private System.Threading.SendOrPostCallback DaneKomunikatOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UslugaBIRzewnPubl() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::FakturaWpf.Properties.Settings.Default.FakturaWpf_pl_gov_stat_wyszukiwarkaregontest_UslugaBIRzewnPubl;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PobierzCaptchaCompletedEventHandler PobierzCaptchaCompleted;
        
        /// <remarks/>
        public event SprawdzCaptchaCompletedEventHandler SprawdzCaptchaCompleted;
        
        /// <remarks/>
        public event SetValueCompletedEventHandler SetValueCompleted;
        
        /// <remarks/>
        public event GetValueCompletedEventHandler GetValueCompleted;
        
        /// <remarks/>
        public event ZalogujCompletedEventHandler ZalogujCompleted;
        
        /// <remarks/>
        public event WylogujCompletedEventHandler WylogujCompleted;
        
        /// <remarks/>
        public event DaneSzukajCompletedEventHandler DaneSzukajCompleted;
        
        /// <remarks/>
        public event DanePobierzPelnyRaportCompletedEventHandler DanePobierzPelnyRaportCompleted;
        
        /// <remarks/>
        public event DaneKomunikatCompletedEventHandler DaneKomunikatCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptcha", RequestNamespace="http://CIS/BIR/2014/07", ResponseNamespace="http://CIS/BIR/2014/07", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PobierzCaptcha() {
            object[] results = this.Invoke("PobierzCaptcha", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PobierzCaptchaAsync() {
            this.PobierzCaptchaAsync(null);
        }
        
        /// <remarks/>
        public void PobierzCaptchaAsync(object userState) {
            if ((this.PobierzCaptchaOperationCompleted == null)) {
                this.PobierzCaptchaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPobierzCaptchaOperationCompleted);
            }
            this.InvokeAsync("PobierzCaptcha", new object[0], this.PobierzCaptchaOperationCompleted, userState);
        }
        
        private void OnPobierzCaptchaOperationCompleted(object arg) {
            if ((this.PobierzCaptchaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PobierzCaptchaCompleted(this, new PobierzCaptchaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptcha", RequestNamespace="http://CIS/BIR/2014/07", ResponseNamespace="http://CIS/BIR/2014/07", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SprawdzCaptcha([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pCaptcha, out bool SprawdzCaptchaResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SprawdzCaptchaResultSpecified) {
            object[] results = this.Invoke("SprawdzCaptcha", new object[] {
                        pCaptcha});
            SprawdzCaptchaResult = ((bool)(results[0]));
            SprawdzCaptchaResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SprawdzCaptchaAsync(string pCaptcha) {
            this.SprawdzCaptchaAsync(pCaptcha, null);
        }
        
        /// <remarks/>
        public void SprawdzCaptchaAsync(string pCaptcha, object userState) {
            if ((this.SprawdzCaptchaOperationCompleted == null)) {
                this.SprawdzCaptchaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSprawdzCaptchaOperationCompleted);
            }
            this.InvokeAsync("SprawdzCaptcha", new object[] {
                        pCaptcha}, this.SprawdzCaptchaOperationCompleted, userState);
        }
        
        private void OnSprawdzCaptchaOperationCompleted(object arg) {
            if ((this.SprawdzCaptchaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SprawdzCaptchaCompleted(this, new SprawdzCaptchaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CIS/BIR/2014/07/IUslugaBIR/SetValue", RequestNamespace="http://CIS/BIR/2014/07", ResponseNamespace="http://CIS/BIR/2014/07", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetValue([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pNazwaParametru, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pWartoscParametru) {
            object[] results = this.Invoke("SetValue", new object[] {
                        pNazwaParametru,
                        pWartoscParametru});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetValueAsync(string pNazwaParametru, string pWartoscParametru) {
            this.SetValueAsync(pNazwaParametru, pWartoscParametru, null);
        }
        
        /// <remarks/>
        public void SetValueAsync(string pNazwaParametru, string pWartoscParametru, object userState) {
            if ((this.SetValueOperationCompleted == null)) {
                this.SetValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetValueOperationCompleted);
            }
            this.InvokeAsync("SetValue", new object[] {
                        pNazwaParametru,
                        pWartoscParametru}, this.SetValueOperationCompleted, userState);
        }
        
        private void OnSetValueOperationCompleted(object arg) {
            if ((this.SetValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetValueCompleted(this, new SetValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CIS/BIR/2014/07/IUslugaBIR/GetValue", RequestNamespace="http://CIS/BIR/2014/07", ResponseNamespace="http://CIS/BIR/2014/07", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetValue([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pNazwaParametru) {
            object[] results = this.Invoke("GetValue", new object[] {
                        pNazwaParametru});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetValueAsync(string pNazwaParametru) {
            this.GetValueAsync(pNazwaParametru, null);
        }
        
        /// <remarks/>
        public void GetValueAsync(string pNazwaParametru, object userState) {
            if ((this.GetValueOperationCompleted == null)) {
                this.GetValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetValueOperationCompleted);
            }
            this.InvokeAsync("GetValue", new object[] {
                        pNazwaParametru}, this.GetValueOperationCompleted, userState);
        }
        
        private void OnGetValueOperationCompleted(object arg) {
            if ((this.GetValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetValueCompleted(this, new GetValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj", RequestNamespace="http://CIS/BIR/PUBL/2014/07", ResponseNamespace="http://CIS/BIR/PUBL/2014/07", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Zaloguj([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pKluczUzytkownika) {
            object[] results = this.Invoke("Zaloguj", new object[] {
                        pKluczUzytkownika});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZalogujAsync(string pKluczUzytkownika) {
            this.ZalogujAsync(pKluczUzytkownika, null);
        }
        
        /// <remarks/>
        public void ZalogujAsync(string pKluczUzytkownika, object userState) {
            if ((this.ZalogujOperationCompleted == null)) {
                this.ZalogujOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZalogujOperationCompleted);
            }
            this.InvokeAsync("Zaloguj", new object[] {
                        pKluczUzytkownika}, this.ZalogujOperationCompleted, userState);
        }
        
        private void OnZalogujOperationCompleted(object arg) {
            if ((this.ZalogujCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZalogujCompleted(this, new ZalogujCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Wyloguj", RequestNamespace="http://CIS/BIR/PUBL/2014/07", ResponseNamespace="http://CIS/BIR/PUBL/2014/07", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Wyloguj([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pIdentyfikatorSesji, out bool WylogujResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool WylogujResultSpecified) {
            object[] results = this.Invoke("Wyloguj", new object[] {
                        pIdentyfikatorSesji});
            WylogujResult = ((bool)(results[0]));
            WylogujResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void WylogujAsync(string pIdentyfikatorSesji) {
            this.WylogujAsync(pIdentyfikatorSesji, null);
        }
        
        /// <remarks/>
        public void WylogujAsync(string pIdentyfikatorSesji, object userState) {
            if ((this.WylogujOperationCompleted == null)) {
                this.WylogujOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWylogujOperationCompleted);
            }
            this.InvokeAsync("Wyloguj", new object[] {
                        pIdentyfikatorSesji}, this.WylogujOperationCompleted, userState);
        }
        
        private void OnWylogujOperationCompleted(object arg) {
            if ((this.WylogujCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WylogujCompleted(this, new WylogujCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukaj", RequestNamespace="http://CIS/BIR/PUBL/2014/07", ResponseNamespace="http://CIS/BIR/PUBL/2014/07", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DaneSzukaj([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ParametryWyszukiwania pParametryWyszukiwania) {
            object[] results = this.Invoke("DaneSzukaj", new object[] {
                        pParametryWyszukiwania});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DaneSzukajAsync(ParametryWyszukiwania pParametryWyszukiwania) {
            this.DaneSzukajAsync(pParametryWyszukiwania, null);
        }
        
        /// <remarks/>
        public void DaneSzukajAsync(ParametryWyszukiwania pParametryWyszukiwania, object userState) {
            if ((this.DaneSzukajOperationCompleted == null)) {
                this.DaneSzukajOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDaneSzukajOperationCompleted);
            }
            this.InvokeAsync("DaneSzukaj", new object[] {
                        pParametryWyszukiwania}, this.DaneSzukajOperationCompleted, userState);
        }
        
        private void OnDaneSzukajOperationCompleted(object arg) {
            if ((this.DaneSzukajCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DaneSzukajCompleted(this, new DaneSzukajCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaport", RequestNamespace="http://CIS/BIR/PUBL/2014/07", ResponseNamespace="http://CIS/BIR/PUBL/2014/07", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DanePobierzPelnyRaport([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pRegon, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pNazwaRaportu) {
            object[] results = this.Invoke("DanePobierzPelnyRaport", new object[] {
                        pRegon,
                        pNazwaRaportu});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DanePobierzPelnyRaportAsync(string pRegon, string pNazwaRaportu) {
            this.DanePobierzPelnyRaportAsync(pRegon, pNazwaRaportu, null);
        }
        
        /// <remarks/>
        public void DanePobierzPelnyRaportAsync(string pRegon, string pNazwaRaportu, object userState) {
            if ((this.DanePobierzPelnyRaportOperationCompleted == null)) {
                this.DanePobierzPelnyRaportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDanePobierzPelnyRaportOperationCompleted);
            }
            this.InvokeAsync("DanePobierzPelnyRaport", new object[] {
                        pRegon,
                        pNazwaRaportu}, this.DanePobierzPelnyRaportOperationCompleted, userState);
        }
        
        private void OnDanePobierzPelnyRaportOperationCompleted(object arg) {
            if ((this.DanePobierzPelnyRaportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DanePobierzPelnyRaportCompleted(this, new DanePobierzPelnyRaportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikat", RequestNamespace="http://CIS/BIR/PUBL/2014/07", ResponseNamespace="http://CIS/BIR/PUBL/2014/07", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DaneKomunikat() {
            object[] results = this.Invoke("DaneKomunikat", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DaneKomunikatAsync() {
            this.DaneKomunikatAsync(null);
        }
        
        /// <remarks/>
        public void DaneKomunikatAsync(object userState) {
            if ((this.DaneKomunikatOperationCompleted == null)) {
                this.DaneKomunikatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDaneKomunikatOperationCompleted);
            }
            this.InvokeAsync("DaneKomunikat", new object[0], this.DaneKomunikatOperationCompleted, userState);
        }
        
        private void OnDaneKomunikatOperationCompleted(object arg) {
            if ((this.DaneKomunikatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DaneKomunikatCompleted(this, new DaneKomunikatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CIS/BIR/PUBL/2014/07/DataContract")]
    public partial class ParametryWyszukiwania {
        
        private string krsField;
        
        private string krsyField;
        
        private string nipField;
        
        private string nipyField;
        
        private string regonField;
        
        private string regony14znField;
        
        private string regony9znField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Krs {
            get {
                return this.krsField;
            }
            set {
                this.krsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Krsy {
            get {
                return this.krsyField;
            }
            set {
                this.krsyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nip {
            get {
                return this.nipField;
            }
            set {
                this.nipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nipy {
            get {
                return this.nipyField;
            }
            set {
                this.nipyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Regon {
            get {
                return this.regonField;
            }
            set {
                this.regonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Regony14zn {
            get {
                return this.regony14znField;
            }
            set {
                this.regony14znField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Regony9zn {
            get {
                return this.regony9znField;
            }
            set {
                this.regony9znField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PobierzCaptchaCompletedEventHandler(object sender, PobierzCaptchaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PobierzCaptchaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PobierzCaptchaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SprawdzCaptchaCompletedEventHandler(object sender, SprawdzCaptchaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SprawdzCaptchaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SprawdzCaptchaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SprawdzCaptchaResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SprawdzCaptchaResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SetValueCompletedEventHandler(object sender, SetValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetValueCompletedEventHandler(object sender, GetValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ZalogujCompletedEventHandler(object sender, ZalogujCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZalogujCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZalogujCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WylogujCompletedEventHandler(object sender, WylogujCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WylogujCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WylogujCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool WylogujResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool WylogujResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DaneSzukajCompletedEventHandler(object sender, DaneSzukajCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DaneSzukajCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DaneSzukajCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DanePobierzPelnyRaportCompletedEventHandler(object sender, DanePobierzPelnyRaportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DanePobierzPelnyRaportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DanePobierzPelnyRaportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DaneKomunikatCompletedEventHandler(object sender, DaneKomunikatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DaneKomunikatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DaneKomunikatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591